---
apiVersion: v1
kind: Namespace
metadata:
  name: "molliebot-${ENVIRONMENT}"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: molliebot
  namespace: "molliebot-${ENVIRONMENT}"
spec:
  replicas: 1
  minReadySeconds: 5
  revisionHistoryLimit: 2 # this keeps 2 old replica sets, and removes older replica sets
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: molliebot
    spec:
      containers:
      - image: registry.hub.docker.com/wvdeutekom/molliebot:${IMAGE_TAG}
        name: molliebot
        env:
          - name: CONFIG_LOCATION
            value: "/gopath/molliebot/config.json"
          - name: RESTRICT_TO_CONFIG_CHANNELS
            value: "false"
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: molliebot-secret
                key: slack-api-key
          - name: PAGERDUTY_API_KEY
            valueFrom:
              secretKeyRef:
                name: molliebot-secret
                key: pagerduty-api-key
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /gopath/molliebot
          name: config
      volumes:
        - name: config
          configMap:
            name: molliebot-config
            items:
            - key: config-json
              path: config.json

---
apiVersion: v1
kind: Secret
metadata:
  name: molliebot-secret
  namespace: "molliebot-${ENVIRONMENT}"
type: Opaque
data:
  slack-api-key: "${SLACK_API_KEY}"
  pagerduty-api-key: "${PAGERDUTY_API_KEY}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: molliebot-config
  namespace: molliebot-${ENVIRONMENT}
data:
  config-json: |
    {
      "pagerduty": {
        "report_channels": [
          "G6ARE3RSL"
        ]
      },
      "messages": {
        "restricted_channels": [
          "C594N2UHG",
          "C07J1HXF0"
        ],
        "notification_times": []
      },
      "lunch": {
        "lunches": [
          { "date":"2017-07-03", "description":"Gegrilde italiaanse venkel worstjes met geroosterde paprika feta salade met dadels en een vers libanees platbrood" },
          { "date":"2017-07-05", "description":"Parmigiana di melanzana met taleggio en een radicchio sinaasappel salade, rozemarijn broodjes met kaas" },
          { "date":"2017-07-10", "description":"Gesmoorde indische kokos kip in een licht pittige pinda saus met Gado Gado mega salade, en atjar,krupoek,seroendeng,sambal,gebakken uitjes" },
          { "date":"2017-07-12", "description":"Thaise loempia's met een frisse jonge mango chilli dip en een knaperige oosterse salade met munt,korriander,geroosterde cashew noten en een pittige dressing" },
          { "date":"2017-07-17", "description":"Hele zalm van de plank met mosterd dille en een radicchio artichokken-tomatensalade met rustiek brood" },
          { "date":"2017-07-19", "description":"Knapperige geroosterde hele kip diavola in stukken met courget , rode uien met walnoten avocado pesto en rustiek brood" },
          { "date":"2017-07-24", "description":"Inktvis salade met chorizo knoflook,rucola,tomaten en kikkererwten en rustiek brood" },
          { "date":"2017-07-26", "description":"Geroosterde koteletten,met saffraan tomaten-venkel salade en gratin dauphinois uit de oven" },
          { "date":"2017-07-31", "description":"Geroosterde Kippenpoten afgeblust met zoete pittge ketjap marinade en gestoomde spinazie met basmati kokosrijst , mango chutny en pappadum" }
        ]
      }
    }
